# Generated by Django 3.2.4 on 2021-07-02 07:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=64)),
                ('firstName', models.TextField(max_length=50)),
                ('lastName', models.TextField(max_length=50)),
                ('phNo', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('gender', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainSite.user')),
                ('profilePicture', models.ImageField(upload_to='images/useruploads')),
            ],
        ),
    ]
