# Generated by Django 3.2.4 on 2021-06-21 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
