# Generated by Django 3.2.4 on 2021-07-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0003_detail_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='friends',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
