# Generated by Django 3.2.4 on 2021-06-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_auto_20210622_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
