# Generated by Django 3.2.4 on 2021-07-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainSite', '0004_detail_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='friends',
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('this', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='this', serialize=False, to='mainSite.detail')),
                ('others', models.ManyToManyField(to='mainSite.Detail')),
            ],
        ),
    ]
